#!/usr/bin/python3
"""
Factorize numbers in a file into a product of two prime numbers
"""
import sys


def factorize():
    """
    A function to search file and factorize the given set of numbers
    into two prime numbers (format n = p*q)
    """
    try:
        file = sys.argv[1]
        with open(file) as f:
            for number in f:
                number = int(number)
                if number % 2 == 0:
                    print("{}={}*{}".format(number, number // 2, 2))
                    continue
                i = 3
                while i < number // 2:
                    if number % i == 0:
                        print("{}={}*{}".format(number, number // i, i))
                        break
                    i = i + 2
                if i == (number // 2) + 1:
                    print("{}={}*{}".format(number, number, 1))
    except (IndexError):
        pass


factorize()
